/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'id' : string,
  'status' : AgentStatus,
  'name' : string,
  'email' : string,
  'passwordHash' : string,
  'mobile' : string,
}
export type AgentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface FarmerEKYCApplication {
  'status' : ApplicationStatus,
  'documentReferences' : Array<string>,
  'otherDetails' : string,
  'submittedAt' : bigint,
  'agentId' : string,
  'address' : string,
  'panNumber' : string,
  'mobile' : string,
  'aadhaarNumber' : string,
  'acknowledgmentNumber' : string,
  'farmerName' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'agentId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'agentLogin' : ActorMethod<
    [string, string],
    { 'ok' : Agent } |
      { 'err' : string }
  >,
  'agentLoginWithPhone' : ActorMethod<
    [string, string],
    { 'ok' : Agent } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgentByManager' : ActorMethod<
    [string, string, string, [] | [string]],
    Agent
  >,
  'getAgentById' : ActorMethod<[string], [] | [Agent]>,
  'getApplicationByAckNumber' : ActorMethod<
    [string],
    [] | [FarmerEKYCApplication]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getManagerSession' : ActorMethod<[], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAgents' : ActorMethod<[], Array<Agent>>,
  'listAllApplications' : ActorMethod<[], Array<FarmerEKYCApplication>>,
  'registerAgent' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'requestManagerOtp' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFarmerApplication' : ActorMethod<
    [string, string, string, string, string, string, string, Array<string>],
    string
  >,
  'updateAgentStatus' : ActorMethod<[string, AgentStatus], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [string, ApplicationStatus],
    undefined
  >,
  'verifyManagerOtp' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];