/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AgentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Agent = IDL.Record({
  'id' : IDL.Text,
  'status' : AgentStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const FarmerEKYCApplication = IDL.Record({
  'status' : ApplicationStatus,
  'documentReferences' : IDL.Vec(IDL.Text),
  'otherDetails' : IDL.Text,
  'submittedAt' : IDL.Int,
  'agentId' : IDL.Text,
  'address' : IDL.Text,
  'panNumber' : IDL.Text,
  'mobile' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'acknowledgmentNumber' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'agentId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'agentLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Agent, 'err' : IDL.Text })],
      ['query'],
    ),
  'agentLoginWithPhone' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Agent, 'err' : IDL.Text })],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgentByManager' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Agent],
      [],
    ),
  'getAgentById' : IDL.Func([IDL.Text], [IDL.Opt(Agent)], ['query']),
  'getApplicationByAckNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FarmerEKYCApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getManagerSession' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'listAllApplications' : IDL.Func(
      [],
      [IDL.Vec(FarmerEKYCApplication)],
      ['query'],
    ),
  'registerAgent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'requestManagerOtp' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFarmerApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'updateAgentStatus' : IDL.Func([IDL.Text, AgentStatus], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
  'verifyManagerOtp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AgentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Agent = IDL.Record({
    'id' : IDL.Text,
    'status' : AgentStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const FarmerEKYCApplication = IDL.Record({
    'status' : ApplicationStatus,
    'documentReferences' : IDL.Vec(IDL.Text),
    'otherDetails' : IDL.Text,
    'submittedAt' : IDL.Int,
    'agentId' : IDL.Text,
    'address' : IDL.Text,
    'panNumber' : IDL.Text,
    'mobile' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'acknowledgmentNumber' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'agentId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'agentLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Agent, 'err' : IDL.Text })],
        ['query'],
      ),
    'agentLoginWithPhone' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Agent, 'err' : IDL.Text })],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgentByManager' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Agent],
        [],
      ),
    'getAgentById' : IDL.Func([IDL.Text], [IDL.Opt(Agent)], ['query']),
    'getApplicationByAckNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FarmerEKYCApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getManagerSession' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'listAllApplications' : IDL.Func(
        [],
        [IDL.Vec(FarmerEKYCApplication)],
        ['query'],
      ),
    'registerAgent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'requestManagerOtp' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFarmerApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'updateAgentStatus' : IDL.Func([IDL.Text, AgentStatus], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
    'verifyManagerOtp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };